# 프레임/토픽
base_frame: base_link
odom_frame: odom
map_update_interval: 10.0

# 라이다 범위(필요시 조정)
maxRange: 12.0
maxUrange: 8.0

# 업데이트 조건
linearUpdate: 0.10       # 10cm 움직일 때마다 업데이트
angularUpdate: 0.10      # 0.1rad(≈5.7°) 회전 시 업데이트
temporalUpdate: 0.50     # 0.5초 주기 보조 업데이트

# 필터/입자 (기본값 무난)
particles: 30
xmin: -20.0
ymin: -20.0
xmax:  20.0
ymax:  20.0

# 노이즈 추정(기본값)
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2

# 레이 캐스터 설정
delta: 0.05

